server:
    port: 8084
    
spring:
    application:
        name: Readerservice
    profiles:
        active: default
    cloud:
        config:
            enabled: true
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fatchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        healthcheck:
            enabled: true
management:
    endpoint:
        health:
            show-details: always

        
        
        
        
        
        